ignore_actions:
  # Stable, official, I prefer `v4` style for OSS
  - name: actions/checkout

  # My action
  - name: kachick/wait-other-jobs

  # That version and CLI is in same repository, and I bump it with selfup to sync with nixpkgs
  - name: crate-ci/typos

# Do not add DeterminateSystems actions here, they are using major versions but there are no releases for patch versions
