# https://taskfile.dev

version: '3'

env:
  # If test for nix product: `PLUGIN_PATH="$PWD/result/lib/plugin.wasm" task`
  PLUGIN_PATH: '{{.USER_WORKING_DIR}}/target/wasm32-unknown-unknown/debug/dprint_plugin_kdl.wasm'

tasks:
  default:
    deps:
      - check
      - test
  build: # Prefer cargo cache rather than go-task cache feature
    env:
      SKIP_BUILD: 'false' # Don't use "$CI" for this purpose
      CARGO_BUILD_TARGET: 'wasm32-unknown-unknown'
    status:
      - |
        [ "$SKIP_BUILD" == 'true' ]
    cmds:
      # Omit "--release" for development purpose. Release assets should use `nix build`
      - cargo build
  check:
    deps:
      - test
      - lint
  test:
    deps:
      - test-unit
      - test-e2e
  test-unit:
    env:
      SKIP_BUILD: 'false'
    status:
      - |
        [ "$SKIP_BUILD" == 'true' ]
    cmds:
      - cargo test --workspace
  test-e2e:
    deps:
      - test-e2e-official
      - test-e2e-zellij
      - test-e2e-zellij-v1
  test-e2e-*:
    deps:
      - build
    vars:
      TESTNAME: '{{index .MATCH 0}}'
    cmds:
      - cd 'tests/{{.TESTNAME}}' && dprint check --plugins="$PLUGIN_PATH" expected.kdl
      - cd 'tests/{{.TESTNAME}}' && diff <(cat raw.kdl | dprint fmt --stdin raw.kdl --plugins="$PLUGIN_PATH") expected.kdl
  bump-fixtures-*:
    deps:
      - build
    vars:
      TESTNAME: '{{index .MATCH 0}}'
    cmds:
      - cd 'tests/{{.TESTNAME}}' && cat raw.kdl | dprint fmt --stdin raw.kdl --plugins="$PLUGIN_PATH" > expected.kdl
  bump-fixtures:
    deps:
      - bump-fixtures-official
      - bump-fixtures-zellij
      - bump-fixtures-zellij-v1
  fmt:
    cmds:
      - cargo fmt
      - dprint fmt
  lint:
    cmds:
      - cargo clippy -- --deny warnings
      - cargo fmt --check
      - dprint check
      - typos . .github .vscode
      - zizmor .
      - git ls-files | xargs nix run github:kachick/selfup/v1.3.1 -- list -check
  schema:
    cmds:
      - cargo run --package schemagen
  selfup:
    cmds:
      - git ls-files | xargs nix run github:kachick/selfup/v1.3.1 -- run
