# https://taskfile.dev

version: '3'

tasks:
  default:
    deps:
      - task: check
  build:
    - cargo build --release --target=wasm32-unknown-unknown
  check:
    deps:
      - task: test
      - task: lint
  test:
    deps:
      - build
    cmds:
      - cargo test
      - dprint check --config=dprint-test.json
  fmt:
    cmds:
      - cargo fmt
      - dprint fmt
      - dprint fmt --config=dprint-test.json
      - treefmt
  lint:
    cmds:
      - cargo clippy
      - dprint check
      - typos . .github .vscode
      - zizmor .
      # nix fmt doesn't have check: https://github.com/NixOS/nix/issues/6918
      - git ls-files '*.nix' | xargs nixfmt --check
      - git ls-files | xargs nix run github:kachick/selfup/v1.3.1 -- list -check
  schema:
    cmds:
      - cargo run --package schemagen
  selfup:
    cmds:
      - git ls-files | xargs nix run github:kachick/selfup/v1.3.1 -- run
