name: 'Setup Nix with cache'
description: 'Install Nix and configure Nix store caching'
runs:
  using: 'composite'
  steps:
    - uses: NixOS/nix-installer-action@62c1943b776c509394b550f3f983adc14e9212d6 # v1.0.0
