# https://github.com/NixOS/nixos-artwork/blob/35ebbbf01c3119005ed180726c388a01d4d1100c/logo/README.md#L5
name: ❄️
on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/ci-nix.yml'
      - '**.nix'
      - 'flake.*'
      - '**.rs'
      - 'Cargo.*'
      - 'example'
      - 'Taskfile.yml'
  pull_request:
    paths:
      - '.github/workflows/ci-nix.yml'
      - '**.nix'
      - 'flake.*'
      - '**.rs'
      - 'Cargo.*'
      - 'example'
      - 'Taskfile.yml'
  schedule:
    # Every 10:42 JST
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron: '42 1 * * *'
  workflow_dispatch:

jobs:
  tasks:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          # - macos-14
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@ab6bcb2d5af0e904d04aea750e2089e9dc4cbfdd # v13
      - run: nix develop --command echo 'This step should be done before any other "nix develop" steps because of measuring Nix build time'
      - run: nix flake check
      - run: nix flake show
      - run: nix develop --command task deps
      - run: nix develop --command task
      - run: |
          dprint config add "file:${PWD}/target/wasm32-unknown-unknown/release/dprint_plugin_kdl.wasm"
          dprint output-file-paths | grep -F '.kdl'
      - run: dprint check
        id: dprint-check
        continue-on-error: true
      - run: false
        if: steps.dprint-check.outcome == 'success'
      - run: |
          dprint fmt
          diff ./example/zellij-config.wrong.kdl ./example/zellij-config.expected.kdl
