name: 👕
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  dprint:
    timeout-minutes: 15
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: dprint/check@7dc032d8874778fc024f6f9b4a7e6d896782c330 # v2.5
        with:
          dprint-version: '0.57.4' # selfup {"extract":"\\d[^']+","replacer":["dprint", "--version"], "nth": 2}

  typos:
    timeout-minutes: 15
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: crate-ci/typos@v1.50.2 # selfup {"extract":"\\d\\.\\d+\\.\\d+","replacer":["typos", "--version"], "nth": 2}
        with:
          files: |
            .
            .github
            .vscode
