# https://github.com/NixOS/nixos-artwork/blob/35ebbbf01c3119005ed180726c388a01d4d1100c/logo/README.md#L5
name: ❄️
on:
  push:
    tags:
      # Do not add v prefix: https://github.com/dprint/plugins/blob/75a3755b8734eee294214a7d7efc18145668a99f/README.md?plain=1#L27
      # https://github.com/actions/runner/issues/1699#issuecomment-1046796067
      - '[0-9]+.[0-9]+.[0-9]+'
    branches: [main]
    paths:
      - '.github/workflows/nix.yml'
      - '.github/actions/setup-nix'
      - '**.nix'
      - 'flake.*'
      - '**.rs'
      - 'Cargo.*'
      - 'tests'
      - 'Taskfile.yml'
  pull_request:
    paths:
      - '.github/workflows/nix.yml'
      - '.github/actions/setup-nix'
      - '**.nix'
      - 'flake.*'
      - '**.rs'
      - 'Cargo.*'
      - 'tests'
      - 'Taskfile.yml'
  schedule:
    # Every 10:42 JST
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron: '42 1 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    permissions:
      id-token: 'write'
      contents: 'read'
    runs-on: ubuntu-26.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: $/.github/actions/setup-nix
      # Don't use rust caches since using package.nix, rust cachees are only available in devshell workflow.
      - run: nix build
      - run: tree -h result/
      - name: Upload WASM file as an artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          if-no-files-found: error
          name: 'dist'
          path: |
            result/lib/plugin.wasm
            result/share/schema.json

  flake:
    permissions:
      id-token: 'write'
      contents: 'read'
    runs-on: ubuntu-26.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: $/.github/actions/setup-nix
      # Don't use cache action, this task does not compile the dependencies. And it unexpectedly overrides cache result in build job
      - run: nix flake check
      - run: nix flake show

  CD:
    needs: [build]
    permissions:
      # "contents: write" allows the action to create a release: https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#permissions
      contents: write
      actions: read # For `gh run download`
    uses: $/.github/workflows/CD.yml
    with:
      run_id: '${{ github.run_id }}'
      release: ${{ startsWith(github.ref, 'refs/tags/') }}
